// <auto-generated />
using System;
using ConsoleApp1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(TareasDbContext))]
    [Migration("20201009151950_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("ConsoleApp1.Detalles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRecurso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTareas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecursoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TareasId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tiempo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecursoId");

                    b.HasIndex("TareasId");

                    b.ToTable("Detalle");
                });

            modelBuilder.Entity("ConsoleApp1.Recursos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Recurso");
                });

            modelBuilder.Entity("ConsoleApp1.Tareas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estimacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRecursos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vencimiento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableId");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("ConsoleApp1.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ConsoleApp1.Detalles", b =>
                {
                    b.HasOne("ConsoleApp1.Recursos", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId");

                    b.HasOne("ConsoleApp1.Tareas", "Tareas")
                        .WithMany()
                        .HasForeignKey("TareasId");
                });

            modelBuilder.Entity("ConsoleApp1.Recursos", b =>
                {
                    b.HasOne("ConsoleApp1.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("ConsoleApp1.Tareas", b =>
                {
                    b.HasOne("ConsoleApp1.Recursos", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId");
                });
#pragma warning restore 612, 618
        }
    }
}
